# Generated by Django 5.2.5 on 2025-08-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_generated', models.DateTimeField(auto_now_add=True)),
                ('total_users', models.IntegerField()),
                ('total_bookings', models.IntegerField()),
                ('total_payments', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
    ]
