# Generated by Django 5.2.5 on 2025-08-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminstats',
            name='total_bookings',
        ),
        migrations.AddField(
            model_name='adminstats',
            name='total_dining_bookings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adminstats',
            name='total_event_bookings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adminstats',
            name='total_room_bookings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adminstats',
            name='total_spa_bookings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='adminstats',
            name='total_payments',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='adminstats',
            name='total_users',
            field=models.IntegerField(default=0),
        ),
    ]
