# Generated by Django 5.2.5 on 2025-08-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbooking',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='number_of_guests',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
