# Generated by Django 5.2.5 on 2025-08-17 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(default='Spacious comfort with elegant interior and private balcony view.'),
        ),
    ]
