# Generated by Django 5.2.5 on 2025-08-19 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
