# Generated by Django 5.2.5 on 2025-08-19 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diningreservation',
            options={'ordering': ['-reservation_date', '-reservation_time']},
        ),
        migrations.AddField(
            model_name='diningreservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 8, 19, 8, 47, 44, 671670, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='table',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='diningreservation',
            unique_together={('table', 'reservation_date', 'reservation_time')},
        ),
    ]
