# Generated by Django 5.2.5 on 2025-08-16 23:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(default='Standard', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='member_since',
            field=models.DateField(auto_now_add=True, default=datetime.date(2025, 1, 1)),
            preserve_default=False,
        ),
    ]
