# Generated by Django 5.2.5 on 2025-08-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spaservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='spa_images/'),
        ),
    ]
