# Generated by Django 5.2.5 on 2025-08-16 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spas', '0002_spaservice_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spaservice',
            name='image',
        ),
    ]
