# Generated by Django 5.2.5 on 2025-08-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spas', '0003_remove_spaservice_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='spaservice',
            name='duration_in_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
